### PR TITLE
Feature/improve code

### PR DESCRIPTION
**Pull request by kessiler**

### CODE REVIEW

**Comment by olalonde** [comment]
Thanks for the PR. Would you like to maintain this module? I haven't used in a long time.

**Comment by kessiler** [comment]
I can do it as possible man! :)

**Comment by olalonde** [comment]
Cool! Just make sure you bump the major version in package.json if you break backwards compatibility. What's your npm username? `npm whoami`

**Comment by kessiler** [comment]
Sure man, going forward using semver rules.
My user is kessiler there.

**Comment by olalonde** [comment]
Ok, added you as a collaborator here and as an owner on the npm package :)

**Comment by kessiler** [comment]
@olalonde can you enable issues on this repos?

**Comment by olalonde** [comment]
Yep, just did.

**Pull request merged**
